version: '3'

services:
    mrdb:
        image: mariadb:10.5.2
        restart: unless-stopped
        environment:
            - TZ
            - MYSQL_DATABASE=wp
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
            - mrdb_etc:/etc/mysql/conf.d
            - mrdb_dat:/var/lib/mysql
            - mrdb_log:/var/log/mysql
        command: '--default-authentication-plugin=mysql_native_password'
        ports:
            - "127.0.0.1:3306:3306"
        networks:
            - bknd-net
    fcgi:
        depends_on:
            - mrdb
        image: wordpress:5.4.0-php7.4-fpm-alpine
        restart: unless-stopped
        environment:
            - TZ
            - WORDPRESS_DB_HOST=mrdb:3306
            - WORDPRESS_DB_NAME=wp
            - WORDPRESS_DB_USER=${MYSQL_USER}
            - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - fcgi_etc:/usr/local/etc/php-fpm.d
            - fcgi_dat:/var/www/html
        networks:
            - bknd-net
    wsrv:
        depends_on:
            - fcgi 
        image: nginx:1.17.9-alpine-perl
        restart: unless-stopped
        environment:
            - TZ
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - wsrv_etc:/etc/nginx/conf.d
            - fcgi_dat:/var/www/html
            - cert_dat:/etc/letsencrypt
        networks:
            - bknd-net
    cbot:
        depends_on:
            - wsrv
        image: certbot/certbot
        environment:
            - TZ
        volumes:
            - cert_dat:/etc/letsencrypt
            - fcgi_dat:/var/lib/letsencrypt
        command: --version
        networks:
            - bknd-net
volumes:
    mrdb_dat:
    fcgi_dat:
    cert_dat:
    mrdb_etc:
    fcgi_etc:
    wsrv_etc:
    mrdb_log:

networks:
    bknd-net:
        driver: bridge  
